### ISSUE TITLE
Diseño del menu de navegacion

### ISSUE THREAD

**Issue by isael-Diroche** [Tcriss/RoadRunners-Front#1]
El menu de navegacion de la pagina presenta leves errores diseño al momento de intentar navegar entre las diferentes paginas en un telefono movil se hace imposible ya que solo presenta la opcion de inicio y no permite moverse entre pantallas.

**Comment by Tcriss** [comment]
## Gracias por tu aporte

El error fue corregido en el commit: ***fix: side navigation bar design while scrolling***
